name: build

on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: Build
        run: go build -v -o dist/talksh_${GOOS}_${GOARCH}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: talksh-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/talksh_${{ matrix.goos }}_${{ matrix.goarch }}